--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 5/6/2020 12:17:15 PM
-- Server version: 5.5.5-10.2.31-MariaDB
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE dawpar2;

--
-- Drop view `incident_place_type_view`
--
DROP VIEW IF EXISTS incident_place_type_view CASCADE;

--
-- Drop view `view1`
--
DROP VIEW IF EXISTS view1 CASCADE;

--
-- Drop procedure `addIncident`
--
DROP PROCEDURE IF EXISTS addIncident;

--
-- Drop table `incident_place_type`
--
DROP TABLE IF EXISTS incident_place_type;

--
-- Drop procedure `addPlace`
--
DROP PROCEDURE IF EXISTS addPlace;

--
-- Drop table `incident_place`
--
DROP TABLE IF EXISTS incident_place;

--
-- Drop procedure `addType`
--
DROP PROCEDURE IF EXISTS addType;

--
-- Drop table `incident_type`
--
DROP TABLE IF EXISTS incident_type;

--
-- Set default database
--
USE dawpar2;

--
-- Create table `incident_type`
--
CREATE TABLE incident_type (
  id int(11) NOT NULL AUTO_INCREMENT,
  typeName varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 12,
AVG_ROW_LENGTH = 2340,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

DELIMITER $$

--
-- Create procedure `addType`
--
CREATE DEFINER = 'construtecmxV2'@'%'
PROCEDURE addType (IN $typeName varchar(255))
BEGIN
  INSERT INTO incident_type (typeName)
    VALUE ($typeName);
END
$$

DELIMITER ;

--
-- Create table `incident_place`
--
CREATE TABLE incident_place (
  id int(11) NOT NULL AUTO_INCREMENT,
  placeName varchar(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 13,
AVG_ROW_LENGTH = 1820,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

DELIMITER $$

--
-- Create procedure `addPlace`
--
CREATE DEFINER = 'construtecmxV2'@'%'
PROCEDURE addPlace (IN $placeName varchar(255))
BEGIN
  INSERT INTO incident_place (placeName)
    VALUE ($placeName);
END
$$

DELIMITER ;

--
-- Create table `incident_place_type`
--
CREATE TABLE incident_place_type (
  id int(11) NOT NULL AUTO_INCREMENT,
  id_place int(11) DEFAULT NULL,
  id_type int(11) DEFAULT NULL,
  dateRegistered datetime DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 10,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create foreign key
--
ALTER TABLE incident_place_type
ADD CONSTRAINT FK_incident_place_type_id_place FOREIGN KEY (id_place)
REFERENCES incident_place (id) ON DELETE NO ACTION;

--
-- Create foreign key
--
ALTER TABLE incident_place_type
ADD CONSTRAINT FK_incident_place_type_id_type FOREIGN KEY (id_type)
REFERENCES incident_type (id) ON DELETE NO ACTION;

DELIMITER $$

--
-- Create procedure `addIncident`
--
CREATE DEFINER = 'construtecmxV2'@'%'
PROCEDURE addIncident (IN $type int, IN $place int)
BEGIN
  INSERT INTO incident_place_type (id_place, id_type)
    VALUE ($place, $type);
END
$$

DELIMITER ;

--
-- Create view `view1`
--
CREATE
DEFINER = 'construtecmxV2'@'%'
VIEW view1
AS
SELECT
  `incident_place_type`.`id` AS `id`,
  `incident_place`.`placeName` AS `placeName`,
  `incident_type`.`typeName` AS `typeName`,
  `incident_place_type`.`dateRegistered` AS `dateRegistered`,
  `incident_place_type`.`id_place` AS `id_place`,
  `incident_place_type`.`id_type` AS `id_type`
FROM ((`incident_place_type`
  JOIN `incident_place`
    ON (`incident_place_type`.`id_place` = `incident_place`.`id`))
  JOIN `incident_type`
    ON (`incident_place_type`.`id_type` = `incident_type`.`id`));

--
-- Create view `incident_place_type_view`
--
CREATE
DEFINER = 'construtecmxV2'@'%'
VIEW incident_place_type_view
AS
SELECT
  `incident_place_type`.`id` AS `id`,
  `incident_place`.`placeName` AS `placeName`,
  `incident_type`.`typeName` AS `typeName`,
  `incident_place_type`.`dateRegistered` AS `dateRegistered`,
  `incident_place_type`.`id_place` AS `id_place`,
  `incident_place_type`.`id_type` AS `id_type`
FROM ((`incident_place_type`
  JOIN `incident_place`
    ON (`incident_place_type`.`id_place` = `incident_place`.`id`))
  JOIN `incident_type`
    ON (`incident_place_type`.`id_type` = `incident_type`.`id`));

-- 
-- Dumping data for table incident_type
--
INSERT INTO incident_type VALUES
(5, 'Falla eléctrica'),
(6, 'Fuga de herbívoro'),
(7, 'Fuga de Velociraptors'),
(8, 'Fuga de TRex'),
(9, 'Robo de ADN'),
(10, 'Auto descompuesto'),
(11, 'Visitantes en zona no autorizada');

-- 
-- Dumping data for table incident_place
--
INSERT INTO incident_place VALUES
(4, 'Centro turístico'),
(5, 'Laboratorios'),
(6, 'Restaurante'),
(7, 'Centro operativo'),
(8, 'Triceratops'),
(9, 'Dilofosaurios'),
(10, 'Velociraptors'),
(11, 'TRex'),
(12, 'Planicie de los herbívoros');

-- 
-- Dumping data for table incident_place_type
--
INSERT INTO incident_place_type VALUES
(8, 4, 6, '2020-05-06 12:16:03'),
(9, 6, 10, '2020-05-06 12:16:11');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;